language: scala
dist: trusty
services:
- docker
scala:
- 2.12.10
jdk:
- oraclejdk8
script:
- sbt test
before_deploy:
- pip install --user release-manager==0.3.0
deploy:
  - provider: script
    skip_cleanup: true
    script: release-manager --config ./.travis/release.yml --check-version --make-version --make-artifact --upload-artifact
    on:
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./.travis/deploy_docker.sh $TRAVIS_TAG
    on:
      tags: true
env:
  global:
  - secure: FpFfqcuDuxasw+P+fj62m/NRFWj9Dov74R/6KjdVVn4YdL1PTsqLc6sqttbcJsbobWX9B70LwKKhlYxyL1fWTx6zUe2owXAxtR0Bw2y0WNT6D4XKtfmJYWcVOSGjKJciURaTS9Hi4vypMp06buul+BguuerxW430I6Oo3xMNZF6MDgEJoS6NPL+rzg4l8aqgq+v9PF56ABcyvpHvLwKURz2FvyVE0rj3IJdetZsme/zRkqy+TXA8kGgX2ABgQxohI3kMgJ0sRxhDPN49Ziqjovwmxdg/DkXQJRRzbY5auI/sL0eOhU0ECEDzpfrQEoDBvfuapPEfd3CGfxgH/puXIs8cOQ4gH4NovUQVwdPkpSq/wCEM1j+w4ueSY4+XHRNTKwMYC9oe+YFFCqmAkF2gysYliMV/75ZXa4MMTiCWmKQZZHuSvFRz+tmIv9v1ey2EFc89LeihlxyaUVPsMRhNCg9NOlQ1VcXjaDFqW7Q0udPCIh/32tsoXtkMd7ZriYvG+KIJDZeRf3coYQ9n6SEhfpkizzT/rHcCCnV3iCuA4h2kUYmQkvztRzYGGdttpcOU4Y36teyXnwDv/cZ9FapPSiroydgj/08jcrgkvonzm2me4ddxR/38LmlrbcG2Q/7AhUj2cgICGLjys1OcjvrvZVsINF2u1kJ3qfH5ng6f2X8=
  - secure: iaLlq1SC9zkAr5GJXCFi7bwhGs0PwkMv4ntehYZOM4HS+jA/uAfTZcVHAEHoCvkKSUpM0o4jZA5hJZM8xeYKl7aheePmFscDgJUSqcrgXlAzzBgrxn54CDy/ezmZfV2BM86e8kiJaWLSu+Znqr0gOjNtbUl5IUPImhGhhDMwyQYI/lXu3RI4kquAtbbwDPpNUR+1HQq1TLTBrq2meQifLah2nK6kAigu+c4P1ESDnciz8h/xTG8tN+z3pX5T2i+VZ5Qb0BChTxC2NPDGXg6ia5rzEmPO963xiIQdvDrXgBBy2uEmXQzS7AgERiGPtsiE/tlh9G2uJedGEdI2b6jJ0L7UFFj39F4vch28j6HUBfm/CVTzCiRWJq2kSp8exboDntP7kqi6pjClahIbvyUsLelkpmVWmj8E50qWK2e+5HZG5Saosuau3r1giRyJN8zkv/0taliTfZWZWKKLdWzb3EdP3sDrCE7ZIYMOCPqgzdviJ/U5AMrcN7QKmbD5C/wpL3ixrwBr16bYglgzrVrIAX973mYvKaIjlgYtNKGckGFyekRgfR0aOnKzVn3nBCg4ssLeMFJW1COHu8EdwGgiIJ7T62oVehqSA6QYeDFNi0UDtegSUpngLLQRhAJ8tgS2BGJNdZgC5A286GY/59vb9NjoTIvsYJ8FBRC+G3qc180=
  - secure: chVAt7rsRVeHqUh09PaLUk3yDqyqPIhyi+349gnz0IBeJPT+5Zp6wncRq8uLDijwyk0Vi+metAxq6U0QOEe+ubuOFKiDnZtykcHCul5Bkka6SFHGbz3DBHmnqivOD4JbhuDkCv5iJbp64BlmWa0OlDrrZ1+7/RchVYvW8FcpYTmmQ4IRL4tC5LbaNGiqnCFaUMXVe/wE2c7PiPZnioZfAU1QcZ7UjFfn2R3FCDk9D+hAxM8YcOZ8CTNdosNkjygCWIOM5IU5FvCO4MkbxqX4yLeldaUZH4XMA7mZoNPGmbkZZHudjEdYedBGWQOv26nEOewfNnjb+3HPsLlgBNrodq/hFjCQpAcy3fLoI8bKt6Qns3YZXYF2zkzDgKcq2Y7TsW/pZN7kzqPwNK4oagMAVAzdeyW63w6uplhhD6LWOF2OMJS/QAabHtPx1D9/cbgyscUK75pCsKGUT8Pq6McHkL4WT2qe1ed2hkHspDQFpRleKr3ySeZz30vMBTtyZCM77IAntmAzqrVpG5aAQzxhgxzLBToezTPqlvz7xO9fopKYgKMAK4seUv0IkXraljjwYuznwkV6oR1gOK2K+86cX7yKxN29cECVzM+CrXtjNv8mEVG3N2j85z+a8/+MTIADE4vA3tF2rfBwOKaxPTAYXhFaVtqIjeOlKRjUvWtHgw8=
  - secure: N0meVJgZVNyqUEVIZP2nN5s4rsyqcrRo+c8ddnEkZEkMd59wKx27zWyGcn+53GWA/yax/Z7SF+NNo/+sD2sZuRIBOpMTSa0Bhr07AEQ1oA4jHjoE9mWp3Y2pdj7McW7eBhJUVqlbl3SFn44qiKk7TL0DXCCUhBhVEdKZG3IA34jJdxPzrk0z/yT/EUZqzHqCHe6g3ugxTqH9nuDbHZnwPGrBBjhgdQnQMKNPnhflXyMZY24zIIeds2f6ppPjRM5idGBMK8vlqd88Vk5QXlguHlsi1P7P/vCP8Z35JWAbArqe11YKUxn5b0p2plaPFcEl/qvQ/rukwMX038o4+X1Az6dtSB7sFXjgtOV2WlVRlsgD9mqH4D58jD1LQLOTHYtISz18pL/oxZh3ELK+bkNHutVcVmwVOb2C5c2chMCWm0ra7Dvr0SJQgvQmZVkefmM+Veqy4dIfgsEb7wGshhT5T4DtHObI6xDXNRf06P9rOlr7yu5x2GXAqiIpO9FwWTE+35lgxp6Wqb5p9Oq7VL4hTjtfNsE7SBgZxuQjcMvmv6pc1zmrGA6BOQmPVZVtgIacLXUVtFkMZRPwdiei5ZB/+twxZpniSFqR/SGUEbBAtUk2MUasVjBwhVXhvDHGmo930bDMnk0WmIdvguxyAhwrHx86/7smKj+r0+invOPrNIQ=
