addSbtPlugin("org.scalameta"             % "sbt-scalafmt"           % "2.3.2")
addSbtPlugin("org.scalastyle"            %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager"    % "1.3.6")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"          % "0.9.0")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"           % "0.9.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"           % "0.1.13")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                % "0.4.0")
